name: Build and deploy demo

on:
  push:
    branches: "main"

jobs:
  build-and-deploy:
    name: "Build and deploy"
    env:
      workspace_root: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools'
      qt_version: '6.8.1'
      qt_host_arch: 'gcc_64'
      qt_target_arch: 'wasm_singlethread'
      qt_modules: 'qtquick3d qtshadertools'
      qt_root: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools/Qt'
      target_folder: 'QtQuick3D-Tools'
      source_folder: '/home/runner/work/QtQuick3D-Tools/QtQuick3D-Tools/build/example'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'recursive'
          lfs: 'true'
 
      - name: Install tools
        shell: bash
        run: |
          sudo apt-get -y install jq lftp brotli expect

      - name: Update CMake
        uses: lukka/get-cmake@latest

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Install Qt for host architecture
        uses: Kidev/install-qt-action@v4.2.0
        with:
          version: ${{ env.qt_version }}
          host: 'all_os'
          target: 'wasm'
          arch: 'wasm_singlethread'
          dir: ${{ env.workspace_root }}
          modules: ${{ env.qt_modules }}
          aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@wasm'
          extra: '--autodesktop'

      - name: Verify Qt Installation
        shell: bash
        run: |
          ls -la ${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_host_arch }}/lib
          ls -la ${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_target_arch }}/lib
          ls -la ${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_host_arch }}/lib/cmake
          ls -la ${{ env.qt_root }}/${{ env.qt_version }}/${{ env.qt_target_arch }}/lib/cmake
          
      - name: CMake Build
        shell: bash
        run: |
          make web \
            QT_ROOT=${{ env.qt_root }} \
            QT_VERSION=${{ env.qt_version }} \
            QT_HOST_ARCH=${{ env.qt_host_arch }} \
            QT_TARGET_ARCH=${{ env.qt_target_arch }}

      - name: Upload to FTP
        shell: bash
        run: |
          lftp -u "${{ secrets.FTP_UPLOAD_USER }}","${{ secrets.FTP_UPLOAD_PW }}" ${{ secrets.FTP_UPLOAD_IP }} <<EOF
          set ssl:verify-certificate no
          mirror -R --only-newer --verbose ${{ env.source_folder }} ${{ env.target_folder }}
          quit
          EOF
